Venteformations/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
    path('', include('main.urls')),

]

main/urls.py
from django.urls import path
from .import views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
]

menu/urls.py
from django.urls import path
from .import views
app_name = 'menu'
urlpatterns = [
    path('', views.index, name='index'),
]

main/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models


class Formation(models.Model):
    nom = models.CharField(max_length=500)
    description = models.TextField(max_length=10000)
    prix = models.IntegerField(default=0)

    def __str__(self):
        return self.nom
# Create your models here.

main/views.py
from django.shortcuts import render


# from django.http import HttpResponse

def index(request):
    return render(request, 'main/index.html')
# Create your views here.

menu/views.py
from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponse
from .models import Formation


def index(request):
    """ formations = Formation.objects.all()
    pizza_name_price = [formation.nom + ": " + str(formation.prix) + " F"for formation in formations]
    pizza_name_price_str = ", ".join(pizza_name_price)
    return HttpResponse('Les Formations:' + pizza_name_price_str)"""
    formations = Formation.objects.all().order_by("prix")
    return render(request, 'menu/index.html', {'formations': formations})

def api_get_formations(request):
    formations = Formation.objects.all().order_by("prix")
    json = serializers.serialize("json", formations)
    return HttpResponse(json)

# Create your views here.

main/templates/main/index.html
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FORMATIONS</title>
    <link rel="stylesheet" href="{% static 'main/style.css'%}">
</head>
<body>
<div class="centered">
    <img src="{%static 'main/images/mai_logo.png'%}">
    <a href="{%url 'menu:index'%}">voir les formations</a>
    <div class="para">
    <p style="color:green;font-weight:bold;">Besoin d'une formation qui se figure pas dans la liste?</p>
    <p style="color:green;font-weight:bold;">Contacter moi pour en acquerir d'autres au <a style="display:inline;hover;" href="tel:22870436043">70436043</a></p>
    </div>


</div>
</body>
</html>

menu/templates/menu/index.html
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste des formations</title>
    <link rel="stylesheet" href="{%static 'menu/style.css'%}">
</head>
<body>
    <a href="{%url 'main:index' %}"><img id="small_logo" src="{%static 'menu/images/small_logo.png'%}"></a>
    <div class="menu_title">
    <h1>Les formations</h1>
    </div>
    <div class="menu_list">
        {% for formation in formations %}
        <div class="menu_list_item">
            <span class="menu_list_title">{{formation.nom|upper}}<span>
            <span class="menu_list_prix">{{formation.prix}}F<span>

            <span class="menu_list_description">{{formation.description}}<span>
        </div>
        {%endfor%}
    </div>
</body>
</html>